name: 404ping CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Testing
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Basic sanity check
        run: |
          404ping  --help || true

  cd:
    name: Build & Push Docker Image
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t toklas2004/404ping:latest .

      - name: Push Docker image
        run: |
          docker push toklas2004/404ping:latest
